#!/usr/bin/env bash
# Copyright 2025 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

export SLURMCTLD_OPTIONS="${SLURMCTLD_OPTIONS:-} $*"

# Cleans up any orphan processes that were generated by the original
# process on a reconfigure.
trap 'cleanup' SIGINT SIGTERM EXIT

cleanup() {
    trap - SIGINT SIGTERM EXIT
    kill -- -$$
}

main() {
    opts=( $SLURMCTLD_OPTIONS )
    /usr/sbin/slurmctld --systemd "${opts[@]}"
}

main
